### ISSUE TITLE
deps: NestJS 12, TypeScript 7 and react-table 9 land as deliberate upgrades

### ISSUE THREAD

**Issue by Sumit1993** [prismalens/prismalens#688]
## Goal
Move the three held-back dependency majors on purpose, one branch each, instead of leaving red Dependabot PRs open.

## Done when
- [ ] NestJS 12: every `@nestjs/*` package moves in one branch (the `nestjs-major` group from #687), the v11→v12 migration notes are applied, and CI is green.
- [ ] TypeScript 7: `tsconfig` resolves `@types/node` again (`TS2591: Cannot find name 'node:fs'` on #576), and `pnpm typecheck` passes across the workspace.
- [ ] `@tanstack/react-table` 9: every table moves off the removed v8 API (`useReactTable`, `getCoreRowModel`, `getSortedRowModel`, `getPaginationRowModel`, per #572), with the frontend e2e green.

## Pointers
- #590 - deps: NestJS 12 must land as one coordinated bump — five split dependabot PRs cannot pass individually (diagnosis; folded into #601, which closed without it)
- #601 - U5: repo hygiene: changesets, scripts, seed, layout
- #687 - ci(dependabot): group @nestjs/* majors into one PR
- #617, #618 - @nestjs/common and @nestjs/platform-express 12, closed
- #576 - typescript 7.0.2, closed; #572 - @tanstack/react-table 9.2.4, closed
- #590's hold ("no dependency churn until 0.5.0 is on latest") ended when 0.5.0 reached npm on 2026-09-19.

Posted by an agent under the operator's account.

**Comment by Sumit1993** [comment]
The grouped Nest major is open as #689 - chore(deps): bump the nestjs-major group across 1 directory with 6 updates, the group added by #687 - ci(dependabot): group @nestjs/* majors into one PR. The NestJS 12 part of this issue can start from it.

Posted by an agent under the operator's account.
