### ISSUE TITLE
deps: NestJS 12 must land as one coordinated bump — five split dependabot PRs cannot pass individually

### ISSUE THREAD

**Issue by Sumit1993** [prismalens/prismalens#590]
## Why five dependabot PRs could never merge

Dependabot opened one PR per NestJS package for the v12 major:

| PR | Package | From → To |
|---|---|---|
| #579 | `@nestjs/core` | 11.2.1 → 12.0.1 |
| #578 | `@nestjs/testing` | 11.2.1 → 12.0.1 |
| #577 | `@nestjs/config` | 4.0.4 → 12.0.0 |
| #574 | `@nestjs/serve-static` | 5.0.5 → 12.0.0 |
| #573 | `@nestjs/swagger` | 11.4.7 → 12.0.1 |

Every one of them is red, for the same reason. From #579's `Test (ubuntu-latest, Node 22)`,
run `34060837230`:

```
Error: Cannot find module '.../@nestjs+core@12.0.1_@nestjs+common@11.2.1.../@nestjs/common/internal'
       imported from .../@nestjs/core/metadata-scanner.js
```

`@nestjs/core@12` reaches into `@nestjs/common/internal`, which does not exist in
`@nestjs/common@11`. Each PR therefore pins one v12 package against v11 peers and dies on import.

**Merging them one at a time does not work either.** Every intermediate state is the same mixed
pair, so there is no ordering that keeps CI green. This is not a flake and not a rebase problem.

Note `@nestjs/common` itself has no PR in the set, because it is a catalog entry these packages
resolve through rather than a direct dependency dependabot opened separately.

## What this actually needs

One branch that moves the whole NestJS surface together:

1. Bump `@nestjs/common` alongside core, testing, config, serve-static and swagger in one commit.
2. Read the v11 → v12 migration notes and fix what it broke. This is the real work; the version
   numbers are the easy part.
3. `@nestjs/cli` is already on 12 — #575 merged separately at `e647b2e` because it is a
   devDependency with no runtime coupling, and it was green on its own.

## Scope note

Post-R1. Nothing in R1 needs NestJS 12, and the standing instruction from the changeset-verbosity
ruling of 2026-09-07 is no non-blocking dependency or CI churn until 0.5.0 is on `latest`.

The five PRs are being closed rather than left open: each carried a permanently-red check set that
dependabot kept rebasing, and the diagnosis is recorded here and in a comment on each PR. Closing
them does not lose anything — dependabot reopens the group when the constraint changes.

**Docs surfaces:** none affected — a dependency major with no user-facing surface until the
migration notes say otherwise; if v12 changes anything in the API's observable behaviour, that is
named in the implementing PR. **Capability tier:** free.

**Comment by Sumit1993** [comment]
Folded into #601. Work continues there.
